services:
  ServicioUs:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    image: userservice-api:1.0
    container_name: userservice_svc
    ports:
      - "6430:80"
      - "6431:443"
    volumes:
      - ./Certs/https:/https/
    env_file:
      - ./Envs/app.env
    restart: always
    networks:
      - services_default
networks:
  services_default:
    external: true
